language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: j6xfhUG151RkCDBAOZJtAxEdOpJRJqrTQHWLdrQH9lQ2YbcbEj+X9hUwzU09R3P1IneKf1yGU/vlBuYMPQ4mD/23V7h2qp9pciw/yIN9NAuFwoNrlO/3Ii5hQ2biEg+tPeU1o41XrGAE4+b7ByIZiieIYHFWSDFUTwG+N+RYgsT6mAaBI1hhDp9UkGSnNmWtFkRXXeW93T/fqk+GhR3GTCrgP/SHXl/VQERaDB7ukzaOmkop/bLa10Ah1gpw0MRHNmHBc6DNjjj7qAa8LpuCgQ4/HrMdpNVMpPdT8CTZ6hwxGYYtEbu9lEsXF47yNwVjNA3XWJmgM1Y4Mcs6ztk7qgI80Fs/Ob6+tFrzrSBeD6UCsTbkoVFUHaodpl9n3cbpiRI/wgWgywzwlkU8k93SnpkrZuUwbiTzmitatccI4u6MJyDr3P5PFQ0yudx/xBYAYoDy6yTYMGTN5j+iZZy08UzZADO52BjnKkgS1bT9yIssi7wrA/+4zv/ocJe1wcQOSjXonPAEajPzu035xid8ehma6rc8Lp2cG/FLHxtM0wj7by7s1/KJWUmSoSfllDtFvezfwn4vLZYjXj/f1At8LIrE7HbAJcdSHuSA28kS9LpuW+IPLYrwgqPbOkJ6feWwxL3hN3kdaB+oh+fiPdrKhCn2hgm8JDcBrsJOyV/z70E=
